## Learning boolean operations with neural networks

In [2]:
# Importing necessary libraries
import numpy as np 
import random
from keras.models import Sequential
from keras.layers import Dense, Flatten

#### Implement OR

In [3]:
# Define logical or (only for training!)
def logical_or(values):
    if values[0] == 1 or values[1] == 1:
        return 1
    return 0

In [4]:
# Generate some training data
X = [[random.randint(0,1), random.randint(0,1)] for x in range(1000)]
y = [logical_or(x) for x in X]

In [10]:
# Print our input and output data
print('Input vectors (X): %s' % X[:5])
print('Target variable (y): %s' % y[:5])

Input vectors (X): [[0, 0], [0, 1], [1, 1], [1, 0], [1, 1]]
Target variable (y): [0, 1, 1, 1, 1]


In [17]:
# Defining our trivial network with a single layer, a tanh activation function and a bias unit
model = Sequential()
model.add(Dense(1, input_shape=(2,), activation='tanh', use_bias=True))
model.compile(optimizer="SGD", loss="mean_squared_error", metrics=['accuracy'])

In [18]:
# Training our model with the generated training data
model.fit(np.array(X), np.array(y), epochs=10, verbose=1)

Epoch 1/10
1000/1000 [==============================] - 0s 189us/step - loss: 0.0098 - acc: 1.0000
Epoch 2/10
1000/1000 [==============================] - 0s 63us/step - loss: 0.0093 - acc: 1.0000
Epoch 3/10
1000/1000 [==============================] - 0s 64us/step - loss: 0.0090 - acc: 1.0000
Epoch 4/10
1000/1000 [==============================] - 0s 63us/step - loss: 0.0087 - acc: 1.0000
Epoch 5/10
1000/1000 [==============================] - 0s 70us/step - loss: 0.0084 - acc: 1.0000
Epoch 6/10
1000/1000 [==============================] - 0s 69us/step - loss: 0.0082 - acc: 1.0000
Epoch 7/10
1000/1000 [==============================] - 0s 70us/step - loss: 0.0081 - acc: 1.0000
Epoch 8/10
1000/1000 [==============================] - 0s 72us/step - loss: 0.0079 - acc: 1.0000
Epoch 9/10
1000/1000 [==============================] - 0s 67us/step - loss: 0.0078 - acc: 1.0000
Epoch 10/10
1000/1000 [==============================] - 0s 66us/step - loss: 0.0077 - acc: 1.0000


In [19]:
# Evaluate our model with some validation data
model.predict(np.array([[1,0],[1,1],[0,0],[0,1]]))

array([[ 0.88151067],
       [ 0.99109834],
       [ 0.04673347],
       [ 0.87854779]], dtype=float32)

In [20]:
# Visualize the weights of the model
for layer in model.layers:
    print(layer.get_weights())

[array([[ 1.33573616],
       [ 1.32259905]], dtype=float32), array([ 0.04676754], dtype=float32)]


#### Implement AND

In [33]:
# We define logical and (only for training!)
def logical_and(values):
    if values[0] == 1 and values[1] == 1:
        return 1
    return 0

In [34]:
# Generate some training data
X = [[random.randint(0,1), random.randint(0,1)] for x in range(1000)]
y = [logical_and(x) for x in X]

In [35]:
# Print our input and output data
print('Input vectors (X): %s' % X[:5])
print('Target variable (y): %s' % y[:5])

Input vectors (X): [[0, 0], [0, 1], [1, 0], [1, 0], [1, 1]]
Target variable (y): [0, 0, 0, 0, 1]


In [39]:
# Defining our trivial network with a single layer, a tanh activation function and a bias unit
model = Sequential()
model.add(Dense(1, input_shape=(2,), activation='tanh', use_bias=True))
model.compile(optimizer="SGD", loss="mean_squared_error", metrics=['accuracy'])

In [40]:
# Training our model with the generated training data
model.fit(np.array(X), np.array(y), epochs=50, verbose=1)

Epoch 1/50
1000/1000 [==============================] - 0s 239us/step - loss: 0.2229 - acc: 0.5060
Epoch 2/50
1000/1000 [==============================] - 0s 74us/step - loss: 0.1741 - acc: 0.7340
Epoch 3/50
1000/1000 [==============================] - 0s 71us/step - loss: 0.1377 - acc: 0.7850
Epoch 4/50
1000/1000 [==============================] - 0s 71us/step - loss: 0.1147 - acc: 0.7850
Epoch 5/50
1000/1000 [==============================] - 0s 70us/step - loss: 0.1016 - acc: 0.8660: 0s - loss: 0.1039 - acc: 0.838
Epoch 6/50
1000/1000 [==============================] - 0s 70us/step - loss: 0.0951 - acc: 1.0000
Epoch 7/50
1000/1000 [==============================] - 0s 73us/step - loss: 0.0913 - acc: 1.0000
Epoch 8/50
1000/1000 [==============================] - 0s 70us/step - loss: 0.0888 - acc: 1.0000
Epoch 9/50
1000/1000 [==============================] - 0s 74us/step - loss: 0.0870 - acc: 1.0000
Epoch 10/50
1000/1000 [==============================] - 0s 74us/step - loss: 0.0855 

In [41]:
# Evaluate our model with some validation data
model.predict(np.array([[1,0],[1,1],[0,0],[0,1]]))

array([[ 0.28036863],
       [ 0.63472402],
       [-0.24683933],
       [ 0.20616394]], dtype=float32)

In [42]:
# Visualize the weights of the model
for layer in model.layers:
    print(layer.get_weights())

[array([[ 0.54012638],
       [ 0.46120593]], dtype=float32), array([-0.25204426], dtype=float32)]


#### Implement XNOR

In [43]:
# We define logical xnor (only for training!)
def logical_xnor(values):
    if values[0] == 1 and values[1] == 1:
        return 1
    if values[0] == 0 and values[1] == 0:
        return 1
    return 0

In [44]:
# Generate some training data
X = [[random.randint(0,1), random.randint(0,1)] for x in range(1000)]
y = [logical_xnor(x) for x in X]

In [45]:
# Thats what xnor is
[logical_xnor(x) for x in [[1,0],[1,1],[0,0],[0,1]]]

[0, 1, 1, 0]

In [67]:
# Defining our trivial network with a single layer, a tanh activation function and a bias unit
model = Sequential()
model.add(Dense(2, input_shape=(2,), activation='tanh', use_bias=True))
model.add(Dense(1, activation='tanh', use_bias=True))
model.compile(optimizer="SGD", loss="mean_squared_error", metrics=['accuracy'])

In [68]:
# Training our model with the generated training data
model.fit(np.array(X), np.array(y), epochs=100, verbose=1, batch_size=10)

Epoch 1/100
1000/1000 [==============================] - 1s 568us/step - loss: 0.3342 - acc: 0.4900
Epoch 2/100
1000/1000 [==============================] - 0s 254us/step - loss: 0.2509 - acc: 0.4970
Epoch 3/100
1000/1000 [==============================] - 0s 240us/step - loss: 0.2488 - acc: 0.5730
Epoch 4/100
1000/1000 [==============================] - 0s 239us/step - loss: 0.2486 - acc: 0.5150
Epoch 5/100
1000/1000 [==============================] - 0s 253us/step - loss: 0.2480 - acc: 0.6270
Epoch 6/100
1000/1000 [==============================] - 0s 257us/step - loss: 0.2473 - acc: 0.5680
Epoch 7/100
1000/1000 [==============================] - 0s 235us/step - loss: 0.2470 - acc: 0.6170
Epoch 8/100
1000/1000 [==============================] - 0s 240us/step - loss: 0.2463 - acc: 0.6870
Epoch 9/100
1000/1000 [==============================] - 0s 249us/step - loss: 0.2456 - acc: 0.7290
Epoch 10/100
1000/1000 [==============================] - 0s 252us/step - loss: 0.2449 - acc: 0.7080

In [69]:
# Evaluate our model with some validation data
model.predict(np.array([[1,0],[1,1],[0,0],[0,1]]))

array([[ 0.0085232 ],
       [ 0.94722325],
       [ 0.9309516 ],
       [ 0.00631127]], dtype=float32)

#### Exercise: Implement XOR

In [104]:
# We define logical xor (only for training!)
def logical_xor(values):
    if values[0] == 0 and values[1] == 1:
        return 1
    if values[0] == 1 and values[1] == 0:
        return 1
    return 0

In [105]:
# Generate some training data
X = [[random.randint(0,1), random.randint(0,1)] for x in range(1000)]
y = [logical_xor(x) for x in X]

In [106]:
# Print our input and output data
print('Input vectors (X): %s' % X[:8])
print('Target variable (y): %s' % y[:8])

Input vectors (X): [[1, 1], [1, 1], [1, 0], [1, 1], [0, 0], [1, 0], [1, 1], [0, 1]]
Target variable (y): [0, 0, 1, 0, 0, 1, 0, 1]


In [115]:
# Create testing and validation split
X_train = X[:500]
y_train = y[:500]
X_validation = X[500:]
y_validation = y[500:]

In [127]:
# -------------------------------------------------------------------------------
# TODO: Implement the neural network and achieve an accuracy greater than 0.7
# -------------------------------------------------------------------------------

In [ ]:
from keras.callbacks import ModelCheckpoint   
import livelossplot as lp

plot_learning = lp.PlotLossesKeras()

# train the model
checkpointer = ModelCheckpoint(filepath='xor.model.weights.best.hdf5', verbose=1, 
                               save_best_only=True)

callbacks = [checkpointer, plot_learning]

# Training our model with the generated training data
model.fit(np.array(X), np.array(y), validation_data=(np.array(X_validation), np.array(y_validation)), 
          callbacks = callbacks, epochs=100, verbose=1)

In [ ]:
# load the weights that yielded the best validation accuracy
model.load_weights('xor.model.weights.best.hdf5')

# Evaluate our model with some validation data
model.predict(np.array([[1,0],[1,1],[0,0],[0,1]]))

In [ ]:
X_test = [[random.randint(0,1), random.randint(0,1)] for x in range(50)]
y_test = [logical_xor(x) for x in X_test]
score = model.evaluate(np.array(X_test), np.array(y_test), verbose=1)
print('\n', 'Model Accuracy: %.3f' % score[1])